#! /home/chenry/perl5/perlbrew/perls/perl-5.16.0/bin/perl

use strict;
use Cwd;
use File::Basename;
use File::Spec;

sub magic_number_matches {
  return 0 unless -e '_build/magicnum';
  local *FH;
  open FH, '_build/magicnum' or return 0;
  my $filenum = <FH>;
  close FH;
  return $filenum == 987991;
}

my $progname;
my $orig_dir;
BEGIN {
  $^W = 1;  # Use warnings
  $progname = basename($0);
  $orig_dir = Cwd::cwd();
  my $base_dir = '/home/chenry/kbase/deploy';
  if (!magic_number_matches()) {
    unless (chdir($base_dir)) {
      die ("Couldn't chdir($base_dir), aborting\n");
    }
    unless (magic_number_matches()) {
      die ("Configuration seems to be out of date, please re-run 'perl Build.PL' again.\n");
    }
  }
  unshift @INC,
    (
     '/homes/chenry/.cpanm/work/1356412344.10584',
     '/home/chenry/kbase/deploy/local/lib/perl5/x86_64-linux',
     '/home/chenry/kbase/deploy/local/lib/perl5',
     '/homes/chenry/kbase/ModelSEED/local/lib/perl5/x86_64-linux',
     '/homes/chenry/kbase/ModelSEED/local/lib/perl5',
     '/homes/chenry/kbase/ModelSEED/lib',
     '/homes/chenry/kbase/ModelSEED/local/lib/perl5/x86_64-linux/auto',
     '/homes/chenry/kbase/KBaseClient/local/lib/perl5/x86_64-linux',
     '/homes/chenry/kbase/KBaseClient/local/lib/perl5',
     '/homes/chenry/kbase/KBaseClient/lib',
     '/homes/chenry/kbase/KBaseClient/local/lib/perl5/x86_64-linux/auto',
     '/homes/chenry/kbase/deploy/../workspace_service/lib',
     '/homes/chenry/kbase/deploy/../KBaseFBAModeling/lib',
     '/homes/chenry/kbase/deploy/../cluster_service/client/perl/Bio-KBase-ClusterService-0.02/lib',
     '/homes/chenry/kbase/deploy/../idserver/lib',
     '/homes/chenry/kbase/deploy/../kb_seed/lib',
     '/homes/chenry/kbase/deploy/local/lib/perl5/x86_64-linux',
     '/homes/chenry/kbase/deploy/local/lib/perl5',
     '/homes/chenry/kbase/deploy/local/lib/perl5/x86_64-linux/auto',
     '/homes/chenry/kbase/KBaseFBAModeling/lib'
    );
}

close(*DATA) unless eof(*DATA); # ensure no open handles to this script

use Module::Build;
Module::Build->VERSION(q{0});

# Some platforms have problems setting $^X in shebang contexts, fix it up here
$^X = Module::Build->find_perl_interpreter;

if (-e 'Build.PL' and not Module::Build->up_to_date('Build.PL', $progname)) {
   warn "Warning: Build.PL has been altered.  You may need to run 'perl Build.PL' again.\n";
}

# This should have just enough arguments to be able to bootstrap the rest.
my $build = Module::Build->resume (
  properties => {
    config_dir => '_build',
    orig_dir => $orig_dir,
  },
);

$build->dispatch;
